apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Giovani-RodriguesS/CI-CD.git
    targetRevision: HEAD
    path: env-config/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc 
    namespace: argocd

  syncPolicy:
    syncOptions:
    automated:
      selfHeal: true
      prune: true