resources:
- ../../base
namespace: dev
namePrefix: dev-
patches:
- target:
    kind: Deployment
    name: myapp
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: grafana/grafana
    - op: replace
      path: /spec/template/spec/containers/0/ports/0/containerPort
      value: 3000