services:
  go-api:
    container_name: go-api
    image: api-test
    build: .
    environment:
      ENV: docker
      DB_URL: host=go-db port=5432 user=postgres password=1234 sslmode=disable
      DB_SELECTED: loja
    ports: 
     - "8080:8080"
    depends_on:
     - go-db
  go-db:
    container_name: go-db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}