apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-db
spec:
  template:
    spec:
      containers:
      - name: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: "1234"
        - name: POSTGRES_USER 
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard