resources:
- ../../base
namespace: stg
namePrefix: stg-
patches:
- target:
    kind: Deployment
    name: myapp
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: nginx
    - op: replace
      path: /spec/template/spec/containers/0/ports/0/containerPort
      value: 8000
- target:
    kind: Service
    name: myapp-service
  patch: |-
    - op: replace
      path: /spec/ports/0/port
      value: 8000
    - op: replace
      path: /spec/ports/0/targetPort
      value: 80